name = "gameping"
main = "worker.mjs"
compatibility_date = "2026-05-14"
workers_dev = true
preview_urls = false

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
VAPID_PUBLIC_KEY = "BKZW3AuE_RBMVMLL4bDKDVsIUtjlxyRxX7HZ5PwiPjMndx3CkzI727hxEzG1frhE19O32aoRmGbXmvJliAEPZs8"
VAPID_SUBJECT = "mailto:gameping@example.com"

[[d1_databases]]
binding = "DB"
database_name = "gameping-db"
database_id = "360af53f-22bc-480b-bdcf-938d0fb075cc"
migrations_dir = "./migrations"
